### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by duncanwp**
Adding day three notebooks and links to additional resources.

Could you check you're happy with this and add a testing notebook (if you have one - I don't for the PyCharm stuff).

### CODE REVIEW

**Comment by duncanwp** [comment]
I've just noticed the layout of your f2py stuff - sorry I only looked at the content... Would you mind moving the notebook into course_content/notebooks and the fortran files into course_content/resources, I think it just makes everything more consistent!

**Comment by ajdawson** [comment]
I wanted to keep the notebooks alongside the custom code, since I'll be compiling the fortran code into a python module during the lecture and I want it to be importable in the notebook without messing with paths. The way I have it now is self-contained.

**Comment by ajdawson** [comment]
I probably won't have a notebook for testing, probably just a directory with source file and test file. I haven't written this content yet so subject to change!

**Comment by duncanwp** [comment]
OK, fair enough. I'll update the Readme

**Comment by ajdawson** [comment]
Cheers, The barotropic model will be the same system, a separate directory with everything in. Currently that is a separate repository. We could leave it separate, copy it over, or make it a submodule. I have no strong feelings.

**Comment by duncanwp** [comment]
Sure. I'd leave the model in a separate repository, but include any presentation / tutorial notebooks in this one I think

**Comment by ajdawson** [comment]
Well, I've set it up so the model isn't installed, is just in the same directory as the notebook, much like the f2py structure. We should just port over the whole thing (not a lot of stuff) into its own directory within the course_content directory.

**Pull request merged**
